import { PageHead, Metric, Card, Badge } from '@/components/ui';
import { Users, UserCheck, ShieldCheck, Clock3, Plus } from 'lucide-react';
const roles=['Admin','Manager','Supervisor','Cashier','Inventory Manager','Accountant'];
const perms=['Price Change','Discount Approval','Refunds','Cancel Sale','Open Cash Drawer','View Cost Price','Inventory Changes','Delete Products','Reports Access','Profit View','User Management'];
const allowed:Record<string,number[]>={Admin:[0,1,2,3,4,5,6,7,8,9,10],Manager:[0,1,2,3,4,5,6,8,9],Supervisor:[0,1,2,3,4,6,8],Cashier:[4], 'Inventory Manager':[5,6,7,8],Accountant:[5,8,9]};
export default function UsersPage(){return <>
<PageHead title="Users, Roles & Permissions" subtitle="Granular access control for administrators, managers, supervisors, cashiers, inventory and accounting teams."><button className="btn btn-primary"><Plus size={15}/> Add User</button></PageHead>
<div className="grid metrics"><Metric label="Total Users" value="28" delta="7.7%" Icon={Users}/><Metric label="Active Users" value="24" delta="9.1%" Icon={UserCheck}/><Metric label="Roles" value="8" delta="6 built-in + custom" Icon={ShieldCheck}/><Metric label="Pending Approvals" value="3" delta="Needs review" Icon={Clock3}/><Metric label="2FA Enabled" value="92%" delta="Admins 100%" Icon={ShieldCheck}/></div>
<div className="grid two-col"><Card title="Users"><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Store</th><th>Status</th><th>Last Login</th></tr></thead><tbody>{[['Alex Morgan','Admin','Main Store'],['Sarah Johnson','Cashier','Main Store'],['Michael Chen','Supervisor','Outlet'],['Jessica Lee','Inventory Manager','Main Warehouse'],['David Wilson','Accountant','All Stores']].map((r,i)=><tr key={r[0]}><td><div className="product-cell"><div className="thumb">👤</div>{r[0]}</div></td><td>{r[1]}</td><td>{r[2]}</td><td><Badge>Active</Badge></td><td>May {18-i}, 2025</td></tr>)}</tbody></table></div></Card><Card title="Security & Access"><div className="list"><div className="list-row"><div className="grow">Manager PIN Override</div><Badge>Enabled</Badge></div><div className="list-row"><div className="grow">Two-factor Authentication</div><Badge>Enabled</Badge></div><div className="list-row"><div className="grow">Session Timeout</div><b>15 min</b></div><div className="list-row"><div className="grow">Device Registration</div><Badge>Required</Badge></div></div></Card></div>
<div className="section-title">Role Permission Matrix</div><Card><div className="table-wrap"><table><thead><tr><th>Permission</th>{roles.map(r=><th key={r}>{r}</th>)}</tr></thead><tbody>{perms.map((p,idx)=><tr key={p}><td>{p}</td>{roles.map(r=><td key={r}><Badge tone={allowed[r]?.includes(idx)?'green':'red'}>{allowed[r]?.includes(idx)?'Allowed':'Denied'}</Badge></td>)}</tr>)}</tbody></table></div></Card>
</>}
