import { PageHead, Metric, Card, Badge } from '@/components/ui';
import { suppliers } from '@/data/mock';
import { ShoppingCart, Clock3, Truck, CheckCircle2, TrendingDown, Plus, Upload, Download } from 'lucide-react';
import { PaymentPie } from '@/components/charts';

export default function Purchases(){
  return <>
    <PageHead title="Purchases & Suppliers" subtitle="Manage suppliers, purchase orders, receiving, returns, invoices and supplier payments.">
      <button className="btn"><Upload size={15}/> Import</button><button className="btn"><Download size={15}/> Export</button><button className="btn btn-primary"><Plus size={15}/> New Purchase Order</button>
    </PageHead>
    <div className="grid metrics"><Metric label="Total Purchases (YTD)" value="$427,630.45" delta="18.6%" Icon={ShoppingCart}/><Metric label="Outstanding Payables" value="$68,923.18" delta="8.4%" Icon={Clock3}/><Metric label="Suppliers" value="48" delta="42 active" Icon={Truck}/><Metric label="On-time Delivery" value="92.6%" delta="4.3%" Icon={CheckCircle2}/><Metric label="Savings (YTD)" value="$13,450.80" delta="12.7%" Icon={TrendingDown}/></div>
    <div className="tabs"><button className="tab active">Overview</button><button className="tab">Purchase Orders</button><button className="tab">GRN</button><button className="tab">Returns</button><button className="tab">Supplier Invoices</button><button className="tab">Payments</button><button className="tab">Suppliers</button><button className="tab">Price Comparison</button><button className="tab">Reorder Suggestions</button></div>
    <div className="grid three-col"><Card title="Purchase Order Summary"><div className="list">{[['Draft','8','$18,450.20'],['Approved','16','$157,280.40'],['Partially Received','12','$98,320.10'],['Fully Received','28','$126,540.30'],['Cancelled','2','$2,150.00']].map(([a,b,c])=><div className="list-row" key={a}><div className="grow">{a}</div><b>{b}</b><span>{c}</span></div>)}</div></Card><Card title="Delivery Performance"><PaymentPie/></Card><Card title="Supplier Spotlight"><div className="list"><div className="list-row"><div className="grow"><div className="title">Global Foods Ltd</div><div className="sub">Preferred supplier · Net 30</div></div><Badge>Preferred</Badge></div><Info k="Credit Limit" v="$50,000.00"/><Info k="Outstanding" v="$18,230.50"/><Info k="On-time Delivery" v="96.2%"/><Info k="Quality Rating" v="★★★★★"/></div></Card></div>
    <div className="grid three-col" style={{marginTop:12}}><Card title="Expected Deliveries (7 days)"><div className="list">{['PO-10256 · Global Foods','$2,450.00 · May 19','PO-10258 · FreshMart','$1,250.00 · May 20'].map((x,i)=><div className="list-row" key={i}><div className="grow">{x}</div></div>)}</div></Card><Card title="Purchase Returns"><div className="list">{['PR-10023 · $125.60','PR-10022 · $85.20','PR-10021 · $62.30'].map(x=><div className="list-row" key={x}><div className="grow">{x}</div><Badge tone="red">Return</Badge></div>)}</div></Card><Card title="Reorder Suggestions"><div className="list">{['Olive Oil · stock 3','Sugar · stock 6','Flour · stock 2','Salt · stock 4'].map(x=><div className="list-row" key={x}><div className="grow">{x}</div><button className="btn btn-sm btn-primary">Add to PO</button></div>)}</div></Card></div>
    <div className="section-title">Purchase Orders</div><Card><div className="toolbar" style={{marginBottom:10}}><select className="field"><option>All Statuses</option><option>Draft</option><option>Approved</option><option>Partially Received</option></select><input className="field" placeholder="Search PO or supplier…"/></div><div className="table-wrap"><table><thead><tr><th>PO #</th><th>Date</th><th>Supplier</th><th>Status</th><th>ETA</th><th>Items</th><th>Amount</th><th>Received</th><th>Balance</th></tr></thead><tbody>{suppliers.map((s,i)=><tr key={s.name}><td>PO-1025{i+2}</td><td>May {18-i}, 2025</td><td>{s.name}</td><td><Badge tone={i===1?'orange':'green'}>{i===1?'Partially Received':'Approved'}</Badge></td><td>May {19+i}, 2025</td><td>{18+i*3}</td><td>${(s.spend*.025).toFixed(2)}</td><td>{i===1?'46%':'0%'}</td><td>${s.outstanding.toFixed(2)}</td></tr>)}</tbody></table></div></Card>
  </>
}
function Info({k,v}:{k:string;v:string}){return <div className="list-row"><div className="grow"><div className="sub">{k}</div><div className="title">{v}</div></div></div>}
