import { PageHead, Card, Badge } from '@/components/ui';
import { Store, Warehouse, Monitor, Barcode, Printer, Scale, CreditCard, QrCode, Plus, ShieldCheck, DatabaseBackup } from 'lucide-react';
export default function Settings(){return <>
<PageHead title="Settings" subtitle="System preferences, stores, warehouses, registers, hardware, taxes, receipts, integrations, backup and security."/>
<div className="tabs"><button className="tab">General</button><button className="tab active">Stores</button><button className="tab">Warehouses</button><button className="tab">Registers</button><button className="tab">Hardware</button><button className="tab">Taxes</button><button className="tab">Receipt Templates</button><button className="tab">Integrations</button><button className="tab">Backup</button><button className="tab">Security</button></div>
<div className="grid three-col">
<Card title="Multi-Store Overview" action={<button className="btn btn-sm"><Plus size={13}/> Add Store</button>}><div className="list">{[['Main Store','3 Registers','Primary'],['Downtown Store','2 Registers','Active'],['Uptown Store','2 Registers','Active'],['Warehouse Outlet','1 Register','Active']].map(([a,b,c])=><div className="list-row" key={a}><Store size={18}/><div className="grow"><div className="title">{a}</div><div className="sub">{b}</div></div><Badge tone={c==='Primary'?'orange':'green'}>{c}</Badge></div>)}</div></Card>
<Card title="Registers" action={<button className="btn btn-sm"><Plus size={13}/> Add Register</button>}><div className="list">{['Register 1 · Main Store','Register 2 · Main Store','Register 3 · Downtown','Register 4 · Uptown','Register 5 · Warehouse Outlet'].map((x,i)=><div className="list-row" key={x}><Monitor size={18}/><div className="grow">{x}</div><Badge tone={i===4?'orange':'green'}>{i===4?'Offline':'Online'}</Badge></div>)}</div></Card>
<Card title="Hardware Status"><div className="small-grid">{[[Barcode,'Barcode Scanner'],[Printer,'Receipt Printer'],[Printer,'Label Printer'],[Monitor,'Cash Drawer'],[Scale,'Weighing Scale'],[Monitor,'Customer Display'],[CreditCard,'Card Terminal'],[QrCode,'QR Display']].map(([Icon,name]:any)=><div className="quick-card" key={name}><Icon size={24}/><h4>{name}</h4><Badge>Connected</Badge></div>)}</div></Card>
<Card title="Tax Configuration" action={<button className="btn btn-sm"><Plus size={13}/> Add Tax</button>}><div className="table-wrap"><table><thead><tr><th>Tax</th><th>Rate</th><th>Type</th><th>Status</th></tr></thead><tbody>{[['Sales Tax','8.25%'],['Food & Beverage','4.00%'],['VAT','12.00%'],['Luxury Tax','15.00%']].map(([a,b],i)=><tr key={a}><td>{a}</td><td>{b}</td><td>Percent</td><td><Badge tone={i===3?'orange':'green'}>{i===3?'Inactive':'Active'}</Badge></td></tr>)}</tbody></table></div></Card>
<Card title="Receipt Templates"><div className="small-grid">{['Classic','Modern Dark','Compact'].map((x,i)=><div className="quick-card" key={x} style={{borderColor:i===1?'var(--accent)':'var(--border)'}}><Printer size={22}/><h4>{x}</h4><p>Logo, header, footer, taxes, QR and custom fields.</p>{i===1&&<Badge tone="orange">Default</Badge>}</div>)}</div></Card>
<Card title="Backup & Security"><div className="list"><div className="list-row"><DatabaseBackup size={18}/><div className="grow"><div className="title">Last Backup</div><div className="sub">May 18, 2025 02:30 AM</div></div><Badge>All good</Badge></div><div className="list-row"><ShieldCheck size={18}/><div className="grow"><div className="title">Two-Factor Authentication</div><div className="sub">Required for privileged roles</div></div><Badge>Enabled</Badge></div><div className="list-row"><Warehouse size={18}/><div className="grow"><div className="title">Synchronization</div><div className="sub">All stores synchronized</div></div><Badge>Synced</Badge></div></div></Card>
</div>
<div className="section-title">Device Registration</div><Card><div className="toolbar"><b>12 registered devices</b><span className="green">● 11 online</span><span className="accent">● 1 offline</span><button className="btn btn-primary" style={{marginLeft:'auto'}}>Register New Device</button></div></Card>
</>}
