import { PageHead, Metric, Card } from '@/components/ui';
import { SalesArea, PaymentPie, SimpleBars } from '@/components/charts';
import { DollarSign, TrendingUp, ReceiptText, Basket, RotateCcw, Download, Sparkles } from 'lucide-react';
import { products, customers } from '@/data/mock';

export default function Reports(){return <>
  <PageHead title="Reports & Analytics" subtitle="Comprehensive sales, profit, inventory, customer, cashier and multi-store analytics."><button className="btn">May 12 – May 18, 2025</button><button className="btn">Compare</button><button className="btn btn-primary"><Download size={15}/> Export Report</button></PageHead>
  <div className="kpi-strip"><Metric label="Total Sales" value="$8,923.60" delta="12.5%" Icon={DollarSign}/><Metric label="Gross Sales" value="$9,842.30" delta="9.8%" Icon={TrendingUp}/><Metric label="Net Sales" value="$8,923.60" delta="12.5%" Icon={ReceiptText}/><Metric label="Profit" value="$3,250.40" delta="15.3%" Icon={TrendingUp}/><Metric label="Avg Basket" value="$57.21" delta="4.7%" Icon={Basket}/><Metric label="Refund Rate" value="1.32%" delta="0.21pp better" Icon={RotateCcw}/></div>
  <Card title="Smart Insights" action={<Sparkles size={16} className="accent"/>}><div className="toolbar"><span>• Beverages grew 18% and contributed 24% of total sales.</span><span>• Friday 6–8 PM is the highest performing time slot.</span><span>• 12 low-stock products may affect upcoming sales.</span></div></Card>
  <div className="grid three-col" style={{marginTop:12}}><Card title="Sales Over Time"><SalesArea/></Card><Card title="Sales by Payment Method"><PaymentPie/></Card><Card title="Sales by Day"><SimpleBars/></Card></div>
  <div className="grid three-col" style={{marginTop:12}}><Card title="Top Products"><div className="list">{products.slice(0,5).map((p,i)=><div className="list-row" key={p.id}><span>{i+1}</span><div className="thumb">{p.emoji}</div><div className="grow">{p.name}</div><b>${(p.price*(120-i*13)).toFixed(2)}</b></div>)}</div></Card><Card title="Top Customers"><div className="list">{customers.slice(0,5).map((c,i)=><div className="list-row" key={c.name}><span>{i+1}</span><div className="grow">{c.name}</div><b>${c.spent.toFixed(2)}</b></div>)}</div></Card><Card title="Top Cashiers"><div className="list">{['Alex Morgan','Sarah Connor','James Carter','Lisa White','David Miller'].map((n,i)=><div className="list-row" key={n}><span>{i+1}</span><div className="grow">{n}</div><b>{142-i*13} sales</b></div>)}</div></Card></div>
  <div className="grid small-grid" style={{marginTop:12}}>{[['Low Stock Impact','12 products','$1,245.30'],['Dead Stock','18 products','$2,340.10'],['Expiring Products','27 products','$1,120.50'],['Purchase Report','12 suppliers','$6,230.40'],['Profit & Loss','Net profit','$3,250.40'],['Inventory Turnover','Current','6.4×'],['Sell-through Rate','Current','72%'],['Avg Days in Inventory','Current','31 days']].map(([t,a,b])=><div className="quick-card" key={t}><h4>{t}</h4><p>{a}</p><div style={{fontSize:20,fontWeight:700,marginTop:8}}>{b}</div></div>)}</div>
</>}
