'use client';
import { ResponsiveContainer, AreaChart, Area, CartesianGrid, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';

const sales = [
  {name:'Mon',sales:2600},{name:'Tue',sales:4100},{name:'Wed',sales:5300},{name:'Thu',sales:4700},{name:'Fri',sales:6800},{name:'Sat',sales:7300},{name:'Sun',sales:8924},
];
export function SalesArea(){ return <div style={{height:230}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={sales}><defs><linearGradient id="orange" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff5a1f" stopOpacity={.42}/><stop offset="1" stopColor="#ff5a1f" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#25282a" vertical={false}/><XAxis dataKey="name" stroke="#72787d" fontSize={10}/><YAxis stroke="#72787d" fontSize={10}/><Tooltip contentStyle={{background:'#151719',border:'1px solid #303336',borderRadius:8}}/><Area type="monotone" dataKey="sales" stroke="#ff5a1f" fill="url(#orange)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div> }
export function PaymentPie(){ const d=[{n:'Cash',v:36},{n:'Card',v:35},{n:'UPI / QR',v:20},{n:'Other',v:9}]; const colors=['#ff5a1f','#5b8cff','#48c774','#9567ff']; return <div style={{height:230}}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={d} dataKey="v" nameKey="n" innerRadius={55} outerRadius={78} paddingAngle={2}>{d.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip contentStyle={{background:'#151719',border:'1px solid #303336',borderRadius:8}}/></PieChart></ResponsiveContainer></div> }
export function SimpleBars(){ return <div style={{height:200}}><ResponsiveContainer width="100%" height="100%"><BarChart data={sales}><CartesianGrid stroke="#25282a" vertical={false}/><XAxis dataKey="name" stroke="#72787d" fontSize={10}/><YAxis stroke="#72787d" fontSize={10}/><Tooltip contentStyle={{background:'#151719',border:'1px solid #303336',borderRadius:8}}/><Bar dataKey="sales" fill="#ff5a1f" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div> }
