'use client';
import { useMemo, useState } from 'react';
import Barcode from 'react-barcode';
import { QRCodeSVG } from 'qrcode.react';
import { products } from '@/data/mock';
import { PageHead, Card, Badge } from '@/components/ui';
import { Printer, Save, FileDown, Search, Plus, Minus } from 'lucide-react';

export default function Barcodes(){
  const [selected,setSelected]=useState<number[]>([1,2,4]); const [copies,setCopies]=useState<Record<number,number>>({1:50,2:50,4:50}); const [type,setType]=useState<'price'|'shelf'>('price'); const [qr,setQr]=useState(true); const [range,setRange]=useState('May 1 – May 18, 2025');
  const chosen=products.filter(p=>selected.includes(p.id)); const total=chosen.reduce((s,p)=>s+(copies[p.id]||1),0); const preview=chosen[0]||products[0];
  const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
  return <>
    <PageHead title="Barcode & Label Printing" subtitle="Generate, preview and print product barcodes, QR codes, price labels and shelf labels.">
      <button className="btn">Label Templates</button><button className="btn">Print History</button>
    </PageHead>
    <div className="card" style={{padding:14,marginBottom:12}}><div className="toolbar"><label><span className="muted" style={{fontSize:11}}>Date Range</span><br/><input className="field" value={range} onChange={e=>setRange(e.target.value)}/></label><label><span className="muted" style={{fontSize:11}}>Purchase Order</span><br/><select className="field"><option>All Purchase Orders</option><option>PO-10255</option></select></label><label><span className="muted" style={{fontSize:11}}>Goods Received</span><br/><select className="field"><option>All Goods Received</option><option>GRN-10586</option></select></label><Badge tone="blue">Date / PO / receiving filters supported</Badge></div></div>
    <div className="grid barcode-layout">
      <Card title="1. Select Products"><label className="global-search" style={{width:'100%',marginBottom:10}}><Search size={14}/><input placeholder="Search product, SKU, barcode…"/></label><div className="list">{products.slice(0,9).map(p=><label className="list-row" key={p.id} style={{cursor:'pointer'}}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/><div className="thumb">{p.emoji}</div><div className="grow"><div className="title">{p.name}</div><div className="sub">{p.sku} · {p.stock} in stock</div></div><b>${p.price.toFixed(2)}</b></label>)}</div></Card>
      <Card title="2. Label Options"><div className="list"><div><div className="muted" style={{fontSize:11,marginBottom:6}}>Label Type</div><div className="toolbar"><button className={`btn ${type==='price'?'btn-primary':''}`} onClick={()=>setType('price')}>Price Label</button><button className={`btn ${type==='shelf'?'btn-primary':''}`} onClick={()=>setType('shelf')}>Shelf Label</button></div></div><div><div className="muted" style={{fontSize:11,marginBottom:6}}>Barcode</div><div className="toolbar"><button className="btn btn-primary">Generate New</button><button className="btn">Use Existing</button></div></div><div><div className="muted" style={{fontSize:11,marginBottom:6}}>Barcode Type</div><select className="field" style={{width:'100%'}}><option>CODE128</option><option>EAN-13</option><option>EAN-8</option><option>UPC</option></select></div><label className="list-row"><div className="grow">Include QR Code</div><input type="checkbox" checked={qr} onChange={e=>setQr(e.target.checked)}/></label><div><div className="muted" style={{fontSize:11,marginBottom:6}}>Preset Size</div><select className="field" style={{width:'100%'}}><option>40mm × 30mm</option><option>50mm × 25mm</option><option>60mm × 40mm</option><option>Custom size</option></select></div><div><div className="muted" style={{fontSize:11,marginBottom:6}}>Printer</div><select className="field" style={{width:'100%'}}><option>Zebra ZD420 (USB)</option><option>TSC TE200</option><option>Browser / PDF</option></select></div></div></Card>
      <Card title={`3. Selected Products (${chosen.length})`} action={<button className="btn btn-sm btn-ghost" onClick={()=>setSelected([])}>Clear All</button>}><div className="list">{chosen.map(p=><div className="list-row" key={p.id}><div className="thumb">{p.emoji}</div><div className="grow"><div className="title">{p.name}</div><div className="sub">{p.sku} · ${p.price.toFixed(2)}</div></div><div className="qty"><button onClick={()=>setCopies(c=>({...c,[p.id]:Math.max(1,(c[p.id]||1)-1)}))}><Minus size={12}/></button><span>{copies[p.id]||1}</span><button onClick={()=>setCopies(c=>({...c,[p.id]:(c[p.id]||1)+1}))}><Plus size={12}/></button></div></div>)}</div><div className="summary-row total"><span>Total Labels</span><span>{total}</span></div></Card>
      <Card title="4. Label Preview" action={<span className="muted" style={{fontSize:11}}>40mm × 30mm</span>}><div className="preview-label"><div className="label-top"><span>{preview.name}</span><span>${preview.price.toFixed(2)}</span></div><div style={{display:'flex',justifyContent:'space-between',fontSize:12,margin:'7px 0 12px'}}><span>SKU: {preview.sku}</span><span>{preview.unit}</span></div><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{flex:1,overflow:'hidden'}}><Barcode value={preview.barcode} height={52} width={1.3} displayValue={false} margin={0}/></div>{qr&&<QRCodeSVG value={`https://pos.local/product/${preview.id}`} size={70}/>}</div></div><div className="toolbar" style={{justifyContent:'center',marginTop:12}}><button className="btn btn-primary"><Printer size={15}/> Print All ({total})</button><button className="btn"><Save size={15}/> Save Template</button><button className="btn"><FileDown size={15}/> Export PDF</button></div></Card>
    </div>
    <div className="section-title">Print Queue</div><Card><div className="table-wrap"><table><thead><tr><th>Job ID</th><th>Created</th><th>Printer</th><th>Labels</th><th>Copies</th><th>Status</th><th></th></tr></thead><tbody><tr><td>LBL-2025-0518-001</td><td>May 18, 2025 10:24 AM</td><td>Zebra ZD420</td><td>{total}</td><td>1</td><td><Badge>Ready</Badge></td><td><button className="btn btn-sm">Print Now</button></td></tr><tr><td>LBL-2025-0518-002</td><td>May 18, 2025 10:15 AM</td><td>TSC TE200</td><td>200</td><td>1</td><td><Badge>Completed</Badge></td><td>…</td></tr></tbody></table></div></Card>
  </>
}
