import { PageHead, Metric, Card, Badge } from '@/components/ui';
import { SalesArea, PaymentPie, SimpleBars } from '@/components/charts';
import { products } from '@/data/mock';
import { Boxes, DollarSign, AlertTriangle, Ban, ArrowDownToLine, ArrowUpFromLine, Plus, Download, Upload } from 'lucide-react';

export default function Inventory(){
  const low=products.filter(p=>p.stock>0&&p.stock<=p.reorder); const out=products.filter(p=>p.stock===0);
  return <>
    <PageHead title="Inventory Management" subtitle="Real-time stock control across stores, warehouses, batches and expiry dates.">
      <button className="btn"><Download size={15}/> Export</button><button className="btn"><Upload size={15}/> Import</button><button className="btn btn-primary"><Plus size={15}/> New Adjustment</button>
    </PageHead>
    <div className="tabs"><button className="tab active">Overview</button><button className="tab">Stock Ledger</button><button className="tab">Stock Movement</button><button className="tab">Batch Tracking</button><button className="tab">Expiry Tracking</button><button className="tab">Stock Take</button><button className="tab">Adjustments</button><button className="tab">Transfers</button><button className="tab">Reorder</button></div>
    <div className="kpi-strip"><Metric label="Inventory Value" value="$124,560.80" delta="8.25%" Icon={DollarSign}/><Metric label="Total Items" value="1,245" delta="All locations" Icon={Boxes}/><Metric label="Low Stock" value="42" delta="12.5%" Icon={AlertTriangle}/><Metric label="Out of Stock" value="16" delta="6.3%" Icon={Ban}/><Metric label="Stock In Today" value="$8,230.00" delta="14.4%" Icon={ArrowDownToLine}/><Metric label="Stock Out Today" value="$5,460.00" delta="7.8%" Icon={ArrowUpFromLine}/></div>
    <div className="grid three-col" style={{marginTop:12}}><Card title="Inventory Value Over Time"><SalesArea/></Card><Card title="Stock Availability"><PaymentPie/></Card><Card title="Stock In vs Out"><SimpleBars/></Card></div>
    <div className="grid small-grid" style={{marginTop:12}}>
      <Card title="Inventory Controls & Policies"><div className="list"><div className="list-row"><div className="grow">FIFO / FEFO</div><Badge>Enabled</Badge></div><div className="list-row"><div className="grow">Negative Stock Restriction</div><Badge>Enabled</Badge></div><div className="list-row"><div className="grow">Multi-Store Inventory</div><Badge>Enabled</Badge></div><div className="list-row"><div className="grow">Auto Reorder</div><Badge>Enabled</Badge></div></div></Card>
      <Card title="Stock Quality"><div className="list"><div className="list-row"><div className="grow"><div className="title">Damaged Stock</div></div><b>12</b></div><div className="list-row"><div className="grow"><div className="title">Expired Stock</div></div><b>18</b></div><div className="list-row"><div className="grow"><div className="title">Lost / Shrinkage</div></div><b>7</b></div></div></Card>
      <Card title="Reorder Suggestions"><div className="list">{low.slice(0,3).map(p=><div className="list-row" key={p.id}><div className="thumb">{p.emoji}</div><div className="grow"><div className="title">{p.name}</div><div className="sub">Reorder to {p.reorder*2}</div></div><button className="btn btn-sm">Order</button></div>)}</div></Card>
      <Card title="Transfers & Receiving"><div className="list"><div className="list-row"><div className="grow"><div className="title">Main Store → Outlet</div><div className="sub">8 transfers in transit</div></div><Badge tone="blue">In Transit</Badge></div><div className="list-row"><div className="grow"><div className="title">Goods Receiving</div><div className="sub">5 receipts pending</div></div><Badge tone="orange">Pending</Badge></div></div></Card>
    </div>
    <div className="section-title">Stock Ledger</div><Card><div className="toolbar" style={{marginBottom:10}}><input className="field" placeholder="Search product, SKU, batch…"/><select className="field"><option>All Stores / Warehouses</option></select><select className="field"><option>All Status</option></select><button className="btn">More Filters</button></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Store / Warehouse</th><th>Current</th><th>Reserved</th><th>Available</th><th>Reorder</th><th>Batch / Lot</th><th>Expiry</th><th>Unit Cost</th><th>Value</th><th>Status</th></tr></thead><tbody>{products.slice(0,10).map((p,i)=>{const available=Math.max(0,p.stock-(i%3));return <tr key={p.id}><td><div className="product-cell"><div className="thumb">{p.emoji}</div>{p.name}</div></td><td>{p.sku}</td><td>{i%3===0?'Main Warehouse':i%3===1?'Main Store':'Outlet Store'}</td><td>{p.stock} {p.unit}</td><td>{i%3}</td><td>{available}</td><td>{p.reorder}</td><td>BATCH-052{i+1}</td><td>{i%4===0?'May 25, 2025':'—'}</td><td>${p.cost.toFixed(2)}</td><td>${(p.cost*p.stock).toFixed(2)}</td><td><Badge tone={p.stock===0?'red':p.stock<=p.reorder?'orange':'green'}>{p.stock===0?'Out of Stock':p.stock<=p.reorder?'Low Stock':'In Stock'}</Badge></td></tr>})}</tbody></table></div></Card>
  </>
}
