<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('register_shifts',function(Blueprint $t){$t->id();$t->foreignId('register_id')->constrained();$t->foreignId('user_id')->constrained();$t->decimal('opening_cash',14,2)->default(0);$t->decimal('expected_cash',14,2)->default(0);$t->decimal('actual_cash',14,2)->nullable();$t->dateTime('opened_at');$t->dateTime('closed_at')->nullable();$t->string('status')->default('open');$t->timestamps();});
  Schema::create('sales',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('store_id')->constrained();$t->foreignId('register_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('shift_id')->nullable()->constrained('register_shifts')->nullOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('type')->default('sale');$t->string('status')->default('completed');$t->decimal('subtotal',14,2);$t->decimal('discount_total',14,2)->default(0);$t->decimal('tax_total',14,2)->default(0);$t->decimal('total',14,2);$t->decimal('paid_total',14,2)->default(0);$t->text('cashier_notes')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('sale_items',function(Blueprint $t){$t->id();$t->foreignId('sale_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete();$t->string('description');$t->decimal('quantity',14,4);$t->decimal('unit_price',14,4);$t->decimal('discount',14,2)->default(0);$t->decimal('tax_rate',8,4)->default(0);$t->decimal('tax_total',14,2)->default(0);$t->decimal('line_total',14,2);$t->timestamps();});
  Schema::create('sale_payments',function(Blueprint $t){$t->id();$t->foreignId('sale_id')->constrained()->cascadeOnDelete();$t->string('method');$t->decimal('amount',14,2);$t->string('reference')->nullable();$t->json('meta')->nullable();$t->timestamps();});
  Schema::create('held_sales',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('store_id')->constrained();$t->foreignId('register_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->json('cart');$t->json('pricing')->nullable();$t->timestamp('held_at');$t->timestamps();});
  Schema::create('cash_movements',function(Blueprint $t){$t->id();$t->foreignId('shift_id')->constrained('register_shifts')->cascadeOnDelete();$t->string('type');$t->decimal('amount',14,2);$t->text('note')->nullable();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('sales_orders',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('store_id')->constrained();$t->string('type')->default('sales_order');$t->string('status')->default('draft');$t->decimal('total',14,2)->default(0);$t->decimal('paid',14,2)->default(0);$t->date('due_date')->nullable();$t->timestamps();});
  Schema::create('expenses',function(Blueprint $t){$t->id();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->string('category');$t->string('description');$t->decimal('amount',14,2);$t->string('payment_method')->nullable();$t->string('receipt_path')->nullable();$t->boolean('recurring')->default(false);$t->string('status')->default('approved');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->date('expense_date');$t->timestamps();});
  Schema::create('accounts',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->string('type');$t->foreignId('parent_id')->nullable()->constrained('accounts')->nullOnDelete();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('journal_entries',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->date('entry_date');$t->text('description')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('journal_lines',function(Blueprint $t){$t->id();$t->foreignId('journal_entry_id')->constrained()->cascadeOnDelete();$t->foreignId('account_id')->constrained();$t->decimal('debit',14,2)->default(0);$t->decimal('credit',14,2)->default(0);$t->timestamps();});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->string('event');$t->string('auditable_type')->nullable();$t->unsignedBigInteger('auditable_id')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->string('ip_address')->nullable();$t->string('device_id')->nullable();$t->timestamps();$t->index(['auditable_type','auditable_id']);});
  Schema::create('integration_connections',function(Blueprint $t){$t->id();$t->string('provider');$t->string('category');$t->json('credentials')->nullable();$t->json('settings')->nullable();$t->timestamp('last_synced_at')->nullable();$t->string('status')->default('connected');$t->timestamps();});
  Schema::create('sync_queue',function(Blueprint $t){$t->id();$t->string('device_id')->nullable();$t->string('entity_type');$t->unsignedBigInteger('entity_id')->nullable();$t->string('action');$t->json('payload');$t->string('status')->default('pending');$t->unsignedInteger('attempts')->default(0);$t->timestamp('synced_at')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['sync_queue','integration_connections','audit_logs','journal_lines','journal_entries','accounts','expenses','sales_orders','cash_movements','held_sales','sale_payments','sale_items','sales','register_shifts'] as $x) Schema::dropIfExists($x);}
};
