<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('categories',function(Blueprint $t){$t->id();$t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('brands',function(Blueprint $t){$t->id();$t->string('name')->unique();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('units',function(Blueprint $t){$t->id();$t->string('name');$t->string('symbol');$t->decimal('precision',4,2)->default(1);$t->timestamps();});
  Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('brand_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('unit_id')->nullable()->constrained()->nullOnDelete();$t->string('sku')->unique();$t->string('name');$t->text('description')->nullable();$t->string('type')->default('simple');$t->decimal('cost_price',14,4)->default(0);$t->decimal('selling_price',14,4)->default(0);$t->decimal('wholesale_price',14,4)->nullable();$t->decimal('member_price',14,4)->nullable();$t->decimal('minimum_price',14,4)->nullable();$t->boolean('tax_inclusive')->default(true);$t->foreignId('tax_rate_id')->nullable();$t->boolean('track_stock')->default(true);$t->boolean('track_batch')->default(false);$t->boolean('track_expiry')->default(false);$t->boolean('track_serial')->default(false);$t->decimal('low_stock_threshold',14,4)->default(0);$t->decimal('reorder_level',14,4)->default(0);$t->string('shelf_location')->nullable();$t->string('status')->default('active');$t->timestamps();});
  Schema::create('product_barcodes',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('barcode')->unique();$t->string('type')->default('EAN13');$t->boolean('primary')->default(false);$t->timestamps();});
  Schema::create('product_images',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('path');$t->unsignedInteger('sort_order')->default(0);$t->timestamps();});
  Schema::create('product_variants',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('sku')->unique();$t->json('attributes');$t->decimal('cost_price',14,4)->nullable();$t->decimal('selling_price',14,4)->nullable();$t->timestamps();});
  Schema::create('product_store_prices',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('store_id')->constrained()->cascadeOnDelete();$t->decimal('selling_price',14,4);$t->decimal('wholesale_price',14,4)->nullable();$t->decimal('member_price',14,4)->nullable();$t->unique(['product_id','store_id']);$t->timestamps();});
  Schema::create('product_bundles',function(Blueprint $t){$t->id();$t->foreignId('parent_product_id')->constrained('products')->cascadeOnDelete();$t->foreignId('child_product_id')->constrained('products')->cascadeOnDelete();$t->decimal('quantity',14,4)->default(1);$t->timestamps();});
  Schema::create('inventory_batches',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('store_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->cascadeOnDelete();$t->string('lot_number')->nullable();$t->date('expiry_date')->nullable();$t->decimal('quantity',14,4)->default(0);$t->decimal('reserved_quantity',14,4)->default(0);$t->decimal('unit_cost',14,4)->default(0);$t->timestamps();$t->index(['product_id','store_id','warehouse_id']);});
  Schema::create('stock_movements',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('batch_id')->nullable()->constrained('inventory_batches')->nullOnDelete();$t->string('type');$t->decimal('quantity',14,4);$t->decimal('unit_cost',14,4)->nullable();$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->text('note')->nullable();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();$t->index(['reference_type','reference_id']);});
  Schema::create('stock_transfers',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->string('from_type');$t->unsignedBigInteger('from_id');$t->string('to_type');$t->unsignedBigInteger('to_id');$t->string('status')->default('draft');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('stock_transfer_items',function(Blueprint $t){$t->id();$t->foreignId('stock_transfer_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->decimal('quantity',14,4);$t->timestamps();});
  Schema::create('stock_adjustments',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->string('reason');$t->decimal('quantity',14,4);$t->text('note')->nullable();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();});
  Schema::create('stock_takes',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->string('type')->default('full');$t->string('status')->default('draft');$t->timestamp('counted_at')->nullable();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();});
 }
 public function down(): void {foreach(['stock_takes','stock_adjustments','stock_transfer_items','stock_transfers','stock_movements','inventory_batches','product_bundles','product_store_prices','product_variants','product_images','product_barcodes','products','units','brands','categories'] as $x) Schema::dropIfExists($x);}
};
