<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('suppliers',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('payment_terms')->nullable();$t->decimal('credit_limit',14,2)->default(0);$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('supplier_products',function(Blueprint $t){$t->id();$t->foreignId('supplier_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('supplier_code')->nullable();$t->decimal('last_cost',14,4)->nullable();$t->decimal('average_cost',14,4)->nullable();$t->unsignedInteger('lead_time_days')->nullable();$t->unique(['supplier_id','product_id']);$t->timestamps();});
  Schema::create('purchase_orders',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('supplier_id')->constrained();$t->foreignId('store_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->nullable()->constrained()->nullOnDelete();$t->string('status')->default('draft');$t->date('expected_date')->nullable();$t->decimal('subtotal',14,2)->default(0);$t->decimal('tax_total',14,2)->default(0);$t->decimal('total',14,2)->default(0);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('purchase_order_items',function(Blueprint $t){$t->id();$t->foreignId('purchase_order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('quantity',14,4);$t->decimal('received_quantity',14,4)->default(0);$t->decimal('unit_cost',14,4);$t->decimal('tax_rate',8,4)->default(0);$t->timestamps();});
  Schema::create('goods_receipts',function(Blueprint $t){$t->id();$t->string('number')->unique();$t->foreignId('purchase_order_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('supplier_id')->constrained();$t->dateTime('received_at');$t->foreignId('received_by')->nullable()->constrained('users')->nullOnDelete();$t->string('status')->default('completed');$t->timestamps();});
  Schema::create('goods_receipt_items',function(Blueprint $t){$t->id();$t->foreignId('goods_receipt_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('quantity',14,4);$t->decimal('unit_cost',14,4);$t->string('lot_number')->nullable();$t->date('expiry_date')->nullable();$t->timestamps();});
  Schema::create('supplier_invoices',function(Blueprint $t){$t->id();$t->foreignId('supplier_id')->constrained();$t->foreignId('purchase_order_id')->nullable()->constrained()->nullOnDelete();$t->string('invoice_number');$t->date('invoice_date');$t->date('due_date')->nullable();$t->decimal('total',14,2);$t->decimal('paid',14,2)->default(0);$t->string('status')->default('unpaid');$t->timestamps();});
  Schema::create('supplier_payments',function(Blueprint $t){$t->id();$t->foreignId('supplier_id')->constrained();$t->foreignId('supplier_invoice_id')->nullable()->constrained()->nullOnDelete();$t->decimal('amount',14,2);$t->string('method');$t->string('reference')->nullable();$t->dateTime('paid_at');$t->timestamps();});
  Schema::create('customer_groups',function(Blueprint $t){$t->id();$t->string('name');$t->string('type')->default('retail');$t->decimal('default_discount',8,4)->default(0);$t->timestamps();});
  Schema::create('customers',function(Blueprint $t){$t->id();$t->foreignId('customer_group_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('address')->nullable();$t->string('membership_level')->nullable();$t->unsignedBigInteger('loyalty_points')->default(0);$t->decimal('wallet_balance',14,2)->default(0);$t->decimal('store_credit',14,2)->default(0);$t->decimal('credit_limit',14,2)->default(0);$t->string('tax_number')->nullable();$t->date('birthday')->nullable();$t->text('notes')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('customer_wallet_transactions',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->string('type');$t->decimal('amount',14,2);$t->decimal('balance_after',14,2);$t->text('note')->nullable();$t->timestamps();});
  Schema::create('loyalty_transactions',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->string('type');$t->bigInteger('points');$t->bigInteger('balance_after');$t->string('reference_type')->nullable();$t->unsignedBigInteger('reference_id')->nullable();$t->timestamps();});
  Schema::create('promotions',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->nullable()->unique();$t->string('type');$t->decimal('value',14,4)->nullable();$t->dateTime('starts_at')->nullable();$t->dateTime('ends_at')->nullable();$t->time('daily_start_time')->nullable();$t->time('daily_end_time')->nullable();$t->decimal('minimum_spend',14,2)->nullable();$t->boolean('member_only')->default(false);$t->boolean('automatic')->default(true);$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('promotion_rules',function(Blueprint $t){$t->id();$t->foreignId('promotion_id')->constrained()->cascadeOnDelete();$t->string('scope');$t->unsignedBigInteger('scope_id')->nullable();$t->decimal('min_quantity',14,4)->nullable();$t->decimal('buy_quantity',14,4)->nullable();$t->decimal('get_quantity',14,4)->nullable();$t->json('conditions')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['promotion_rules','promotions','loyalty_transactions','customer_wallet_transactions','customers','customer_groups','supplier_payments','supplier_invoices','goods_receipt_items','goods_receipts','purchase_order_items','purchase_orders','supplier_products','suppliers'] as $x) Schema::dropIfExists($x);}
};
